In [60]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor


In [61]:
company=pd.read_csv("Company_Data.csv")
company

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [62]:
company.dtypes

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc       object
Age              int64
Education        int64
Urban           object
US              object
dtype: object

In [63]:
company['High'] = company.Sales.map(lambda x: 1 if x>8 else 0)
company['ShelveLoc']=company['ShelveLoc'].astype('category')
company['Urban']=company['Urban'].astype('category')
company['US']=company['US'].astype('category')
company.dtypes
company.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  High  
0         17   Yes  Yes     1  
1         10   Yes  Yes     1  
2         12   Yes  Yes     1  
3         14   Yes  Yes     0  
4         13   Yes   No     0

In [64]:
company['ShelveLoc']=company['ShelveLoc'].cat.codes
company['Urban']=company['Urban'].cat.codes
company['US']=company['US'].cat.codes
company.tail()

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
395  12.57        138     108           17         203    128          1   33   
396   6.14        139      23            3          37    120          2   55   
397   7.41        162      26           12         368    159          2   40   
398   5.94        100      79            7         284     95          0   50   
399   9.71        134      37            0          27    120          1   49   

     Education  Urban  US  High  
395         14      1   1     1  
396         11      0   1     0  
397         18      1   1     0  
398         12      1   1     0  
399         16      1   1     1

In [65]:
array = company.values
X = array[:,0:11]
Y = array[:,11]

In [66]:
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2,random_state=0)

In [67]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [68]:
regressor = RandomForestRegressor(n_estimators = 20, random_state = 0)
regressor.fit(x, y)
y_predict =regressor.predict(x_test)
y_predict

array([0.55, 0.55, 0.75, 0.55, 0.55, 0.55, 0.8 , 0.8 , 0.55, 0.8 , 0.8 ,
       0.8 , 0.55, 0.55, 0.8 , 0.8 , 0.55, 0.8 , 0.8 , 0.8 , 0.75, 0.8 ,
       0.55, 0.55, 0.8 , 0.8 , 0.8 , 0.75, 0.75, 0.75, 0.8 , 0.8 , 0.55,
       0.55, 0.75, 0.8 , 0.75, 0.8 , 0.8 , 0.55, 0.75, 0.55, 0.8 , 0.55,
       0.55, 0.75, 0.8 , 0.55, 0.55, 0.75, 0.55, 0.55, 0.55, 0.8 , 0.55,
       0.55, 0.55, 0.55, 0.55, 0.55, 0.75, 0.55, 0.55, 0.8 , 0.55, 0.8 ,
       0.8 , 0.55, 0.75, 0.8 , 0.55, 0.55, 0.55, 0.8 , 0.8 , 0.55, 0.55,
       0.55, 0.75, 0.55])

In [69]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_predict))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_predict))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_predict)))

Mean Absolute Error: 0.54625
Mean Squared Error: 0.339125
Root Mean Squared Error: 0.5823443998185266


In [70]:
regressor = RandomForestRegressor(n_estimators=50, random_state=0)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
y_pred

array([0.3 , 0.58, 0.26, 0.14, 0.4 , 0.44, 0.68, 0.12, 0.18, 0.12, 0.1 ,
       0.06, 0.14, 0.9 , 0.06, 0.04, 0.88, 0.34, 0.22, 0.06, 0.3 , 0.42,
       0.14, 0.08, 0.22, 0.68, 0.02, 0.36, 0.5 , 0.26, 0.26, 0.88, 0.78,
       0.28, 0.  , 0.78, 0.2 , 0.12, 0.22, 0.32, 0.56, 0.34, 0.14, 0.94,
       0.38, 0.3 , 0.36, 0.66, 0.5 , 0.86, 0.06, 0.32, 0.78, 0.76, 0.18,
       0.48, 0.18, 0.42, 0.46, 0.12, 0.58, 0.86, 0.2 , 0.1 , 0.36, 0.54,
       0.66, 0.82, 0.82, 0.54, 0.72, 0.5 , 0.54, 0.06, 0.28, 0.66, 0.22,
       0.64, 0.62, 0.76])

In [71]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.34700000000000003
Mean Squared Error: 0.17678
Root Mean Squared Error: 0.42045213758524286


In [72]:
regressor = RandomForestRegressor(n_estimators=100, random_state=0)
regressor.fit(x_train, y_train)
y_predi = regressor.predict(x_test)
y_predi

array([0.31, 0.56, 0.32, 0.08, 0.4 , 0.37, 0.7 , 0.12, 0.17, 0.07, 0.11,
       0.07, 0.14, 0.9 , 0.09, 0.08, 0.84, 0.35, 0.2 , 0.03, 0.35, 0.4 ,
       0.13, 0.15, 0.23, 0.68, 0.01, 0.36, 0.47, 0.22, 0.23, 0.93, 0.75,
       0.33, 0.  , 0.82, 0.16, 0.1 , 0.22, 0.31, 0.54, 0.34, 0.14, 0.9 ,
       0.31, 0.3 , 0.42, 0.66, 0.53, 0.92, 0.04, 0.36, 0.82, 0.76, 0.14,
       0.56, 0.23, 0.38, 0.44, 0.15, 0.58, 0.89, 0.18, 0.15, 0.39, 0.61,
       0.75, 0.78, 0.83, 0.51, 0.72, 0.44, 0.6 , 0.15, 0.33, 0.66, 0.17,
       0.62, 0.64, 0.8 ])

In [73]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_predi))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_predi))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_predi)))

Mean Absolute Error: 0.34125
Mean Squared Error: 0.17226249999999999
Root Mean Squared Error: 0.4150451782637644


In [74]:
#Errors decreaing with higher number of trees. compairing 20,50 and 100 trees more accurate is the third one.