In [1]:
import pandas as pd
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [2]:
fraud=pd.read_csv("Fraud_check.csv")
fraud


Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [3]:
fraud["income"]="<=30000"
fraud.loc[fraud["Taxable.Income"]>=30000,"income"]="Good"
fraud.loc[fraud["Taxable.Income"]<=30000,"income"]="Risky"

In [4]:
fraud

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban income  
0                 10   YES   Good  
1                 18   YES   Good  
2                 30   YES   Good  
3                 15   YES   Good  
4                 28    NO   Good  
..               ...   ...    ...  
595                7   YES   Good  
596                2   YES   Good  
597                0   YES   Good  
598               17    NO   Good  
599               16    NO   Good  

[600 rows x 7 columns]

In [5]:
fraud.drop(["Taxable.Income"],axis=1,inplace=True)
fraud

Undergrad Marital.Status  City.Population  Work.Experience Urban income
0          NO         Single            50047               10   YES   Good
1         YES       Divorced           134075               18   YES   Good
2          NO        Married           160205               30   YES   Good
3         YES         Single           193264               15   YES   Good
4          NO        Married            27533               28    NO   Good
..        ...            ...              ...              ...   ...    ...
595       YES       Divorced            39492                7   YES   Good
596       YES       Divorced            55369                2   YES   Good
597        NO       Divorced           154058                0   YES   Good
598       YES        Married           180083               17    NO   Good
599        NO       Divorced           158137               16    NO   Good

[600 rows x 6 columns]

In [6]:
fraud.rename(columns={"Undergrad":"undergrad","Marital.Status":"marital","City.Population":"population",
                      "Work.Experience":"experience","Urban":"urban"},inplace=True)

In [7]:
fraud

undergrad   marital  population  experience urban income
0          NO    Single       50047          10   YES   Good
1         YES  Divorced      134075          18   YES   Good
2          NO   Married      160205          30   YES   Good
3         YES    Single      193264          15   YES   Good
4          NO   Married       27533          28    NO   Good
..        ...       ...         ...         ...   ...    ...
595       YES  Divorced       39492           7   YES   Good
596       YES  Divorced       55369           2   YES   Good
597        NO  Divorced      154058           0   YES   Good
598       YES   Married      180083          17    NO   Good
599        NO  Divorced      158137          16    NO   Good

[600 rows x 6 columns]

In [8]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for column_name in fraud.columns:
    if fraud[column_name].dtype == object:
        fraud[column_name] = le.fit_transform(fraud[column_name])
    else:
        pass

In [9]:
features = fraud.iloc[:,0:5]
labels = fraud.iloc[:,5]


In [10]:
colnames = list(fraud.columns)
predictors = colnames[0:5]
target = colnames[5]

In [11]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size = 0.2,stratify = labels)


In [12]:

from sklearn.ensemble import RandomForestClassifier as RF
model = RF(n_jobs = 3,n_estimators = 15, oob_score = True, criterion = "entropy")
model.fit(x_train,y_train)

C:\Users\bhavy\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:541: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\bhavy\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:545: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /


RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=3,
                       oob_score=True)

In [13]:
model.estimators_
model.classes_
model.n_features_
model.n_classes_

model.n_outputs_

model.oob_score_

0.7333333333333333

In [14]:
prediction = model.predict(x_train)

In [15]:
prediction

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [16]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_train,prediction)

In [25]:
accuracy

0.98125

In [17]:
np.mean(prediction == y_train)

0.98125

In [18]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_train,prediction)


In [24]:
confusion

array([[381,   0],
       [  9,  90]], dtype=int64)

In [19]:
pred_test = model.predict(x_test)

In [22]:
pred_test

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
acc_test =accuracy_score(y_test,pred_test)

In [23]:
acc_test

0.7333333333333333